#pragma once

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP17

#define SERIAL_USART_TX_PIN GP1

#undef SPLIT_USB_DETECT
#define USB_VBUS_PIN GP19