#CAPS_WORD_ENABLE = no
VIA_ENABLE = yes
VIAL_ENABLE = yes

QMK_SETTINGS = yes
# TAP_DANCE_ENABLE = no
# COMBO_ENABLE = no
# KEY_OVERRIDE_ENABLE = no
RGBLIGHT_ENABLE = yes

LTO_ENABLE          = yes

MOUSEKEY_ENABLE     = yes
EXTRAKEY_ENABLE     = yes
COMBO_ENABLE        = yes

